2013-11-22 11:14:54 Error: [MissingComponentException] Component class Log4phpComponent could not be found.
Exception Attributes: array (
  'class' => 'Log4phpComponent',
  'plugin' => false,
)
Request URL: /cakephp/Test/test
Stack Trace:
#0 D:\xampp\htdocs\cakephp\lib\Cake\Controller\ComponentCollection.php(53): ComponentCollection->load('Log4php', Array)
#1 D:\xampp\htdocs\cakephp\lib\Cake\Controller\Controller.php(643): ComponentCollection->init(Object(TestController))
#2 D:\xampp\htdocs\cakephp\lib\Cake\Routing\Dispatcher.php(183): Controller->constructClasses()
#3 D:\xampp\htdocs\cakephp\lib\Cake\Routing\Dispatcher.php(162): Dispatcher->_invoke(Object(TestController), Object(CakeRequest), Object(CakeResponse))
#4 D:\xampp\htdocs\cakephp\app\webroot\index.php(110): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#5 {main}
2013-11-22 11:28:09 Error: [MissingComponentException] Component class Log4phpComponent could not be found.
Exception Attributes: array (
  'class' => 'Log4phpComponent',
  'plugin' => false,
)
Request URL: /cakephp/Test/test
Stack Trace:
#0 D:\xampp\htdocs\cakephp\lib\Cake\Controller\ComponentCollection.php(53): ComponentCollection->load('Log4php', Array)
#1 D:\xampp\htdocs\cakephp\lib\Cake\Controller\Controller.php(643): ComponentCollection->init(Object(TestController))
#2 D:\xampp\htdocs\cakephp\lib\Cake\Routing\Dispatcher.php(183): Controller->constructClasses()
#3 D:\xampp\htdocs\cakephp\lib\Cake\Routing\Dispatcher.php(162): Dispatcher->_invoke(Object(TestController), Object(CakeRequest), Object(CakeResponse))
#4 D:\xampp\htdocs\cakephp\app\webroot\index.php(110): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#5 {main}
2013-11-22 11:33:04 Error: [MissingComponentException] Component class Log4phpComponent could not be found.
Exception Attributes: array (
  'class' => 'Log4phpComponent',
  'plugin' => false,
)
Request URL: /cakephp/Test/test
Stack Trace:
#0 D:\xampp\htdocs\cakephp\lib\Cake\Controller\ComponentCollection.php(53): ComponentCollection->load('Log4php', Array)
#1 D:\xampp\htdocs\cakephp\lib\Cake\Controller\Controller.php(643): ComponentCollection->init(Object(TestController))
#2 D:\xampp\htdocs\cakephp\lib\Cake\Routing\Dispatcher.php(183): Controller->constructClasses()
#3 D:\xampp\htdocs\cakephp\lib\Cake\Routing\Dispatcher.php(162): Dispatcher->_invoke(Object(TestController), Object(CakeRequest), Object(CakeResponse))
#4 D:\xampp\htdocs\cakephp\app\webroot\index.php(110): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#5 {main}
2013-11-22 11:33:26 Error: [MissingComponentException] Component class Log4phpComponent could not be found.
Exception Attributes: array (
  'class' => 'Log4phpComponent',
  'plugin' => false,
)
Request URL: /cakephp/Test/test
Stack Trace:
#0 D:\xampp\htdocs\cakephp\lib\Cake\Controller\ComponentCollection.php(53): ComponentCollection->load('Log4php', Array)
#1 D:\xampp\htdocs\cakephp\lib\Cake\Controller\Controller.php(643): ComponentCollection->init(Object(TestController))
#2 D:\xampp\htdocs\cakephp\lib\Cake\Routing\Dispatcher.php(183): Controller->constructClasses()
#3 D:\xampp\htdocs\cakephp\lib\Cake\Routing\Dispatcher.php(162): Dispatcher->_invoke(Object(TestController), Object(CakeRequest), Object(CakeResponse))
#4 D:\xampp\htdocs\cakephp\app\webroot\index.php(110): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#5 {main}
2013-11-22 11:34:31 Error: [MissingComponentException] Component class Log4phpComponent could not be found.
Exception Attributes: array (
  'class' => 'Log4phpComponent',
  'plugin' => false,
)
Request URL: /cakephp/Test/test
Stack Trace:
#0 D:\xampp\htdocs\cakephp\lib\Cake\Controller\ComponentCollection.php(53): ComponentCollection->load('Log4php', Array)
#1 D:\xampp\htdocs\cakephp\lib\Cake\Controller\Controller.php(643): ComponentCollection->init(Object(TestController))
#2 D:\xampp\htdocs\cakephp\lib\Cake\Routing\Dispatcher.php(183): Controller->constructClasses()
#3 D:\xampp\htdocs\cakephp\lib\Cake\Routing\Dispatcher.php(162): Dispatcher->_invoke(Object(TestController), Object(CakeRequest), Object(CakeResponse))
#4 D:\xampp\htdocs\cakephp\app\webroot\index.php(110): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#5 {main}
2013-11-22 11:34:56 Error: [MissingComponentException] Component class Log4phpComponent could not be found.
Exception Attributes: array (
  'class' => 'Log4phpComponent',
  'plugin' => false,
)
Request URL: /cakephp/Test/test
Stack Trace:
#0 D:\xampp\htdocs\cakephp\lib\Cake\Controller\ComponentCollection.php(53): ComponentCollection->load('Log4php', Array)
#1 D:\xampp\htdocs\cakephp\lib\Cake\Controller\Controller.php(643): ComponentCollection->init(Object(TestController))
#2 D:\xampp\htdocs\cakephp\lib\Cake\Routing\Dispatcher.php(183): Controller->constructClasses()
#3 D:\xampp\htdocs\cakephp\lib\Cake\Routing\Dispatcher.php(162): Dispatcher->_invoke(Object(TestController), Object(CakeRequest), Object(CakeResponse))
#4 D:\xampp\htdocs\cakephp\app\webroot\index.php(110): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#5 {main}
2013-11-22 11:43:14 Error: [MissingComponentException] Component class Log4phpComponent could not be found.
Exception Attributes: array (
  'class' => 'Log4phpComponent',
  'plugin' => false,
)
Request URL: /cakephp/Test/test
Stack Trace:
#0 D:\xampp\htdocs\cakephp\lib\Cake\Controller\ComponentCollection.php(53): ComponentCollection->load('Log4php', Array)
#1 D:\xampp\htdocs\cakephp\lib\Cake\Controller\Controller.php(643): ComponentCollection->init(Object(TestController))
#2 D:\xampp\htdocs\cakephp\lib\Cake\Routing\Dispatcher.php(183): Controller->constructClasses()
#3 D:\xampp\htdocs\cakephp\lib\Cake\Routing\Dispatcher.php(162): Dispatcher->_invoke(Object(TestController), Object(CakeRequest), Object(CakeResponse))
#4 D:\xampp\htdocs\cakephp\app\webroot\index.php(110): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#5 {main}
2013-11-22 11:43:47 Error: [MissingComponentException] Component class Log4phpComponent could not be found.
Exception Attributes: array (
  'class' => 'Log4phpComponent',
  'plugin' => false,
)
Request URL: /cakephp/Test/test
Stack Trace:
#0 D:\xampp\htdocs\cakephp\lib\Cake\Controller\ComponentCollection.php(53): ComponentCollection->load('Log4php', Array)
#1 D:\xampp\htdocs\cakephp\lib\Cake\Controller\Controller.php(643): ComponentCollection->init(Object(TestController))
#2 D:\xampp\htdocs\cakephp\lib\Cake\Routing\Dispatcher.php(183): Controller->constructClasses()
#3 D:\xampp\htdocs\cakephp\lib\Cake\Routing\Dispatcher.php(162): Dispatcher->_invoke(Object(TestController), Object(CakeRequest), Object(CakeResponse))
#4 D:\xampp\htdocs\cakephp\app\webroot\index.php(110): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#5 {main}
2013-11-22 11:46:48 Error: [MissingComponentException] Component class Log4phpComponent could not be found.
Exception Attributes: array (
  'class' => 'Log4phpComponent',
  'plugin' => false,
)
Request URL: /cakephp/Test/test
Stack Trace:
#0 D:\xampp\htdocs\cakephp\lib\Cake\Controller\ComponentCollection.php(53): ComponentCollection->load('Log4php', Array)
#1 D:\xampp\htdocs\cakephp\lib\Cake\Controller\Controller.php(643): ComponentCollection->init(Object(TestController))
#2 D:\xampp\htdocs\cakephp\lib\Cake\Routing\Dispatcher.php(183): Controller->constructClasses()
#3 D:\xampp\htdocs\cakephp\lib\Cake\Routing\Dispatcher.php(162): Dispatcher->_invoke(Object(TestController), Object(CakeRequest), Object(CakeResponse))
#4 D:\xampp\htdocs\cakephp\app\webroot\index.php(110): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#5 {main}
2013-11-22 11:50:35 Error: [MissingComponentException] Component class Log4phpComponent could not be found.
Exception Attributes: array (
  'class' => 'Log4phpComponent',
  'plugin' => false,
)
Request URL: /cakephp/Test/test
Stack Trace:
#0 D:\xampp\htdocs\cakephp\lib\Cake\Controller\ComponentCollection.php(53): ComponentCollection->load('Log4php', Array)
#1 D:\xampp\htdocs\cakephp\lib\Cake\Controller\Controller.php(643): ComponentCollection->init(Object(TestController))
#2 D:\xampp\htdocs\cakephp\lib\Cake\Routing\Dispatcher.php(183): Controller->constructClasses()
#3 D:\xampp\htdocs\cakephp\lib\Cake\Routing\Dispatcher.php(162): Dispatcher->_invoke(Object(TestController), Object(CakeRequest), Object(CakeResponse))
#4 D:\xampp\htdocs\cakephp\app\webroot\index.php(110): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#5 {main}
2013-11-22 11:51:04 Error: [MissingComponentException] Component class Log4phpComponent could not be found.
Exception Attributes: array (
  'class' => 'Log4phpComponent',
  'plugin' => false,
)
Request URL: /cakephp/Test/test
Stack Trace:
#0 D:\xampp\htdocs\cakephp\lib\Cake\Controller\ComponentCollection.php(53): ComponentCollection->load('Log4php', Array)
#1 D:\xampp\htdocs\cakephp\lib\Cake\Controller\Controller.php(643): ComponentCollection->init(Object(TestController))
#2 D:\xampp\htdocs\cakephp\lib\Cake\Routing\Dispatcher.php(183): Controller->constructClasses()
#3 D:\xampp\htdocs\cakephp\lib\Cake\Routing\Dispatcher.php(162): Dispatcher->_invoke(Object(TestController), Object(CakeRequest), Object(CakeResponse))
#4 D:\xampp\htdocs\cakephp\app\webroot\index.php(110): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#5 {main}
2013-11-22 11:51:33 Error: Fatal Error (4): syntax error, unexpected '->' (T_OBJECT_OPERATOR), expecting identifier (T_STRING) or variable (T_VARIABLE) or '{' or '$' in [D:\xampp\htdocs\cakephp\app\Lib\Log\Engine\FirePHPLog.php, line 78]
2013-11-22 11:51:33 Error: [FatalErrorException] syntax error, unexpected '->' (T_OBJECT_OPERATOR), expecting identifier (T_STRING) or variable (T_VARIABLE) or '{' or '$'
Stack Trace:
#0 D:\xampp\htdocs\cakephp\lib\Cake\Error\ErrorHandler.php(205): ErrorHandler::handleFatalError(4, 'syntax error, u...', 'D:\xampp\htdocs...', 78)
#1 [internal function]: ErrorHandler::handleError(4, 'syntax error, u...', 'D:\xampp\htdocs...', 78, Array)
#2 D:\xampp\htdocs\cakephp\lib\Cake\Core\App.php(931): call_user_func('ErrorHandler::h...', 4, 'syntax error, u...', 'D:\xampp\htdocs...', 78, Array)
#3 D:\xampp\htdocs\cakephp\lib\Cake\Core\App.php(904): App::_checkFatalError()
#4 [internal function]: App::shutdown()
#5 {main}
2013-11-22 11:51:33 Error: Fatal Error (4): syntax error, unexpected '->' (T_OBJECT_OPERATOR), expecting identifier (T_STRING) or variable (T_VARIABLE) or '{' or '$' in [D:\xampp\htdocs\cakephp\app\Lib\Log\Engine\FirePHPLog.php, line 78]
2013-11-22 11:51:33 Error: [FatalErrorException] syntax error, unexpected '->' (T_OBJECT_OPERATOR), expecting identifier (T_STRING) or variable (T_VARIABLE) or '{' or '$'
Stack Trace:
#0 D:\xampp\htdocs\cakephp\lib\Cake\Error\ErrorHandler.php(205): ErrorHandler::handleFatalError(4, 'syntax error, u...', 'D:\xampp\htdocs...', 78)
#1 [internal function]: ErrorHandler::handleError(4, 'syntax error, u...', 'D:\xampp\htdocs...', 78, Array)
#2 D:\xampp\htdocs\cakephp\lib\Cake\Core\App.php(931): call_user_func('ErrorHandler::h...', 4, 'syntax error, u...', 'D:\xampp\htdocs...', 78, Array)
#3 D:\xampp\htdocs\cakephp\lib\Cake\Core\App.php(904): App::_checkFatalError()
#4 [internal function]: App::shutdown()
#5 {main}
2013-11-22 11:51:33 Error: Fatal Error (4): syntax error, unexpected '->' (T_OBJECT_OPERATOR), expecting identifier (T_STRING) or variable (T_VARIABLE) or '{' or '$' in [D:\xampp\htdocs\cakephp\app\Lib\Log\Engine\FirePHPLog.php, line 78]
2013-11-22 11:51:33 Error: [FatalErrorException] syntax error, unexpected '->' (T_OBJECT_OPERATOR), expecting identifier (T_STRING) or variable (T_VARIABLE) or '{' or '$'
Stack Trace:
#0 D:\xampp\htdocs\cakephp\lib\Cake\Error\ErrorHandler.php(205): ErrorHandler::handleFatalError(4, 'syntax error, u...', 'D:\xampp\htdocs...', 78)
#1 [internal function]: ErrorHandler::handleError(4, 'syntax error, u...', 'D:\xampp\htdocs...', 78, Array)
#2 D:\xampp\htdocs\cakephp\lib\Cake\Core\App.php(931): call_user_func('ErrorHandler::h...', 4, 'syntax error, u...', 'D:\xampp\htdocs...', 78, Array)
#3 D:\xampp\htdocs\cakephp\lib\Cake\Core\App.php(904): App::_checkFatalError()
#4 [internal function]: App::shutdown()
#5 {main}
2013-11-22 11:51:34 Error: Fatal Error (4): syntax error, unexpected '->' (T_OBJECT_OPERATOR), expecting identifier (T_STRING) or variable (T_VARIABLE) or '{' or '$' in [D:\xampp\htdocs\cakephp\app\Lib\Log\Engine\FirePHPLog.php, line 78]
2013-11-22 11:51:34 Error: [FatalErrorException] syntax error, unexpected '->' (T_OBJECT_OPERATOR), expecting identifier (T_STRING) or variable (T_VARIABLE) or '{' or '$'
Stack Trace:
#0 D:\xampp\htdocs\cakephp\lib\Cake\Error\ErrorHandler.php(205): ErrorHandler::handleFatalError(4, 'syntax error, u...', 'D:\xampp\htdocs...', 78)
#1 [internal function]: ErrorHandler::handleError(4, 'syntax error, u...', 'D:\xampp\htdocs...', 78, Array)
#2 D:\xampp\htdocs\cakephp\lib\Cake\Core\App.php(931): call_user_func('ErrorHandler::h...', 4, 'syntax error, u...', 'D:\xampp\htdocs...', 78, Array)
#3 D:\xampp\htdocs\cakephp\lib\Cake\Core\App.php(904): App::_checkFatalError()
#4 [internal function]: App::shutdown()
#5 {main}
2013-11-22 11:51:49 Error: [MissingComponentException] Component class Log4phpComponent could not be found.
Exception Attributes: array (
  'class' => 'Log4phpComponent',
  'plugin' => false,
)
Request URL: /cakephp/Test/test
Stack Trace:
#0 D:\xampp\htdocs\cakephp\lib\Cake\Controller\ComponentCollection.php(53): ComponentCollection->load('Log4php', Array)
#1 D:\xampp\htdocs\cakephp\lib\Cake\Controller\Controller.php(643): ComponentCollection->init(Object(TestController))
#2 D:\xampp\htdocs\cakephp\lib\Cake\Routing\Dispatcher.php(183): Controller->constructClasses()
#3 D:\xampp\htdocs\cakephp\lib\Cake\Routing\Dispatcher.php(162): Dispatcher->_invoke(Object(TestController), Object(CakeRequest), Object(CakeResponse))
#4 D:\xampp\htdocs\cakephp\app\webroot\index.php(110): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#5 {main}
2013-11-22 11:55:55 Error: [MissingComponentException] Component class Log4phpComponent could not be found.
Exception Attributes: array (
  'class' => 'Log4phpComponent',
  'plugin' => false,
)
Request URL: /cakephp/test
Stack Trace:
#0 D:\xampp\htdocs\cakephp\lib\Cake\Controller\ComponentCollection.php(53): ComponentCollection->load('Log4php', Array)
#1 D:\xampp\htdocs\cakephp\lib\Cake\Controller\Controller.php(643): ComponentCollection->init(Object(TestController))
#2 D:\xampp\htdocs\cakephp\lib\Cake\Routing\Dispatcher.php(183): Controller->constructClasses()
#3 D:\xampp\htdocs\cakephp\lib\Cake\Routing\Dispatcher.php(162): Dispatcher->_invoke(Object(TestController), Object(CakeRequest), Object(CakeResponse))
#4 D:\xampp\htdocs\cakephp\app\webroot\index.php(110): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#5 {main}
2013-11-22 13:49:32 Error: [CakeException] Authentication adapter "User" was not found.
Request URL: /cakephp/
Stack Trace:
#0 D:\xampp\htdocs\cakephp\lib\Cake\Controller\Component\AuthComponent.php(675): AuthComponent->constructAuthenticate()
#1 D:\xampp\htdocs\cakephp\lib\Cake\Controller\Component\AuthComponent.php(303): AuthComponent->_getUser()
#2 [internal function]: AuthComponent->startup(Object(PagesController))
#3 D:\xampp\htdocs\cakephp\lib\Cake\Utility\ObjectCollection.php(132): call_user_func_array(Array, Array)
#4 [internal function]: ObjectCollection->trigger(Object(CakeEvent))
#5 D:\xampp\htdocs\cakephp\lib\Cake\Event\CakeEventManager.php(248): call_user_func(Array, Object(CakeEvent))
#6 D:\xampp\htdocs\cakephp\lib\Cake\Controller\Controller.php(675): CakeEventManager->dispatch(Object(CakeEvent))
#7 D:\xampp\htdocs\cakephp\lib\Cake\Routing\Dispatcher.php(184): Controller->startupProcess()
#8 D:\xampp\htdocs\cakephp\lib\Cake\Routing\Dispatcher.php(162): Dispatcher->_invoke(Object(PagesController), Object(CakeRequest), Object(CakeResponse))
#9 D:\xampp\htdocs\cakephp\app\webroot\index.php(110): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#10 {main}
2013-11-22 14:03:12 Error: [CakeException] Authentication adapter "User" was not found.
Request URL: /cakephp/
Stack Trace:
#0 D:\xampp\htdocs\cakephp\lib\Cake\Controller\Component\AuthComponent.php(675): AuthComponent->constructAuthenticate()
#1 D:\xampp\htdocs\cakephp\lib\Cake\Controller\Component\AuthComponent.php(303): AuthComponent->_getUser()
#2 [internal function]: AuthComponent->startup(Object(PagesController))
#3 D:\xampp\htdocs\cakephp\lib\Cake\Utility\ObjectCollection.php(132): call_user_func_array(Array, Array)
#4 [internal function]: ObjectCollection->trigger(Object(CakeEvent))
#5 D:\xampp\htdocs\cakephp\lib\Cake\Event\CakeEventManager.php(248): call_user_func(Array, Object(CakeEvent))
#6 D:\xampp\htdocs\cakephp\lib\Cake\Controller\Controller.php(675): CakeEventManager->dispatch(Object(CakeEvent))
#7 D:\xampp\htdocs\cakephp\lib\Cake\Routing\Dispatcher.php(184): Controller->startupProcess()
#8 D:\xampp\htdocs\cakephp\lib\Cake\Routing\Dispatcher.php(162): Dispatcher->_invoke(Object(PagesController), Object(CakeRequest), Object(CakeResponse))
#9 D:\xampp\htdocs\cakephp\app\webroot\index.php(110): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#10 {main}
2013-11-22 14:03:44 Error: [MissingControllerException] Controller class UserController could not be found.
Exception Attributes: array (
  'class' => 'UserController',
  'plugin' => NULL,
)
Request URL: /cakephp/user/login
Stack Trace:
#0 D:\xampp\htdocs\cakephp\app\webroot\index.php(110): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#1 {main}
2013-11-22 14:04:22 Error: [CakeException] Authentication adapter "User" was not found.
Request URL: /cakephp/users/login
Stack Trace:
#0 D:\xampp\htdocs\cakephp\lib\Cake\Controller\Component\AuthComponent.php(675): AuthComponent->constructAuthenticate()
#1 D:\xampp\htdocs\cakephp\lib\Cake\Controller\Component\AuthComponent.php(303): AuthComponent->_getUser()
#2 [internal function]: AuthComponent->startup(Object(UsersController))
#3 D:\xampp\htdocs\cakephp\lib\Cake\Utility\ObjectCollection.php(132): call_user_func_array(Array, Array)
#4 [internal function]: ObjectCollection->trigger(Object(CakeEvent))
#5 D:\xampp\htdocs\cakephp\lib\Cake\Event\CakeEventManager.php(248): call_user_func(Array, Object(CakeEvent))
#6 D:\xampp\htdocs\cakephp\lib\Cake\Controller\Controller.php(675): CakeEventManager->dispatch(Object(CakeEvent))
#7 D:\xampp\htdocs\cakephp\lib\Cake\Routing\Dispatcher.php(184): Controller->startupProcess()
#8 D:\xampp\htdocs\cakephp\lib\Cake\Routing\Dispatcher.php(162): Dispatcher->_invoke(Object(UsersController), Object(CakeRequest), Object(CakeResponse))
#9 D:\xampp\htdocs\cakephp\app\webroot\index.php(110): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#10 {main}
2013-11-22 14:04:31 Error: [CakeException] Authentication adapter "User" was not found.
Request URL: /cakephp/users/login
Stack Trace:
#0 D:\xampp\htdocs\cakephp\lib\Cake\Controller\Component\AuthComponent.php(675): AuthComponent->constructAuthenticate()
#1 D:\xampp\htdocs\cakephp\lib\Cake\Controller\Component\AuthComponent.php(303): AuthComponent->_getUser()
#2 [internal function]: AuthComponent->startup(Object(UsersController))
#3 D:\xampp\htdocs\cakephp\lib\Cake\Utility\ObjectCollection.php(132): call_user_func_array(Array, Array)
#4 [internal function]: ObjectCollection->trigger(Object(CakeEvent))
#5 D:\xampp\htdocs\cakephp\lib\Cake\Event\CakeEventManager.php(248): call_user_func(Array, Object(CakeEvent))
#6 D:\xampp\htdocs\cakephp\lib\Cake\Controller\Controller.php(675): CakeEventManager->dispatch(Object(CakeEvent))
#7 D:\xampp\htdocs\cakephp\lib\Cake\Routing\Dispatcher.php(184): Controller->startupProcess()
#8 D:\xampp\htdocs\cakephp\lib\Cake\Routing\Dispatcher.php(162): Dispatcher->_invoke(Object(UsersController), Object(CakeRequest), Object(CakeResponse))
#9 D:\xampp\htdocs\cakephp\app\webroot\index.php(110): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#10 {main}
2013-11-22 14:08:07 Error: [CakeException] Authentication adapter "User" was not found.
Request URL: /cakephp/users/login
Stack Trace:
#0 D:\xampp\htdocs\cakephp\lib\Cake\Controller\Component\AuthComponent.php(675): AuthComponent->constructAuthenticate()
#1 D:\xampp\htdocs\cakephp\lib\Cake\Controller\Component\AuthComponent.php(303): AuthComponent->_getUser()
#2 [internal function]: AuthComponent->startup(Object(UsersController))
#3 D:\xampp\htdocs\cakephp\lib\Cake\Utility\ObjectCollection.php(132): call_user_func_array(Array, Array)
#4 [internal function]: ObjectCollection->trigger(Object(CakeEvent))
#5 D:\xampp\htdocs\cakephp\lib\Cake\Event\CakeEventManager.php(248): call_user_func(Array, Object(CakeEvent))
#6 D:\xampp\htdocs\cakephp\lib\Cake\Controller\Controller.php(675): CakeEventManager->dispatch(Object(CakeEvent))
#7 D:\xampp\htdocs\cakephp\lib\Cake\Routing\Dispatcher.php(184): Controller->startupProcess()
#8 D:\xampp\htdocs\cakephp\lib\Cake\Routing\Dispatcher.php(162): Dispatcher->_invoke(Object(UsersController), Object(CakeRequest), Object(CakeResponse))
#9 D:\xampp\htdocs\cakephp\app\webroot\index.php(110): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#10 {main}
2013-11-22 14:09:58 Error: [CakeException] Authentication adapter "User" was not found.
Request URL: /cakephp/users/login
Stack Trace:
#0 D:\xampp\htdocs\cakephp\lib\Cake\Controller\Component\AuthComponent.php(675): AuthComponent->constructAuthenticate()
#1 D:\xampp\htdocs\cakephp\lib\Cake\Controller\Component\AuthComponent.php(303): AuthComponent->_getUser()
#2 [internal function]: AuthComponent->startup(Object(UsersController))
#3 D:\xampp\htdocs\cakephp\lib\Cake\Utility\ObjectCollection.php(132): call_user_func_array(Array, Array)
#4 [internal function]: ObjectCollection->trigger(Object(CakeEvent))
#5 D:\xampp\htdocs\cakephp\lib\Cake\Event\CakeEventManager.php(248): call_user_func(Array, Object(CakeEvent))
#6 D:\xampp\htdocs\cakephp\lib\Cake\Controller\Controller.php(675): CakeEventManager->dispatch(Object(CakeEvent))
#7 D:\xampp\htdocs\cakephp\lib\Cake\Routing\Dispatcher.php(184): Controller->startupProcess()
#8 D:\xampp\htdocs\cakephp\lib\Cake\Routing\Dispatcher.php(162): Dispatcher->_invoke(Object(UsersController), Object(CakeRequest), Object(CakeResponse))
#9 D:\xampp\htdocs\cakephp\app\webroot\index.php(110): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#10 {main}
2013-11-22 14:10:14 Error: [CakeException] Authentication adapter "User" was not found.
Request URL: /cakephp/users/login
Stack Trace:
#0 D:\xampp\htdocs\cakephp\lib\Cake\Controller\Component\AuthComponent.php(675): AuthComponent->constructAuthenticate()
#1 D:\xampp\htdocs\cakephp\lib\Cake\Controller\Component\AuthComponent.php(303): AuthComponent->_getUser()
#2 [internal function]: AuthComponent->startup(Object(UsersController))
#3 D:\xampp\htdocs\cakephp\lib\Cake\Utility\ObjectCollection.php(132): call_user_func_array(Array, Array)
#4 [internal function]: ObjectCollection->trigger(Object(CakeEvent))
#5 D:\xampp\htdocs\cakephp\lib\Cake\Event\CakeEventManager.php(248): call_user_func(Array, Object(CakeEvent))
#6 D:\xampp\htdocs\cakephp\lib\Cake\Controller\Controller.php(675): CakeEventManager->dispatch(Object(CakeEvent))
#7 D:\xampp\htdocs\cakephp\lib\Cake\Routing\Dispatcher.php(184): Controller->startupProcess()
#8 D:\xampp\htdocs\cakephp\lib\Cake\Routing\Dispatcher.php(162): Dispatcher->_invoke(Object(UsersController), Object(CakeRequest), Object(CakeResponse))
#9 D:\xampp\htdocs\cakephp\app\webroot\index.php(110): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#10 {main}
2013-11-22 14:13:06 Error: Fatal Error (4): syntax error, unexpected ')', expecting ',' or ';' in [D:\xampp\htdocs\cakephp\app\Controller\AppController.php, line 49]
2013-11-22 14:13:06 Error: [FatalErrorException] syntax error, unexpected ')', expecting ',' or ';'
Request URL: /cakephp/
Stack Trace:
#0 D:\xampp\htdocs\cakephp\lib\Cake\Error\ErrorHandler.php(205): ErrorHandler::handleFatalError(4, 'syntax error, u...', 'D:\xampp\htdocs...', 49)
#1 [internal function]: ErrorHandler::handleError(4, 'syntax error, u...', 'D:\xampp\htdocs...', 49, Array)
#2 D:\xampp\htdocs\cakephp\lib\Cake\Core\App.php(931): call_user_func('ErrorHandler::h...', 4, 'syntax error, u...', 'D:\xampp\htdocs...', 49, Array)
#3 D:\xampp\htdocs\cakephp\lib\Cake\Core\App.php(904): App::_checkFatalError()
#4 [internal function]: App::shutdown()
#5 {main}
2013-11-22 14:14:25 Error: Fatal Error (4): syntax error, unexpected ')', expecting ',' or ';' in [D:\xampp\htdocs\cakephp\app\Controller\AppController.php, line 49]
2013-11-22 14:14:25 Error: [FatalErrorException] syntax error, unexpected ')', expecting ',' or ';'
Request URL: /cakephp/
Stack Trace:
#0 D:\xampp\htdocs\cakephp\lib\Cake\Error\ErrorHandler.php(205): ErrorHandler::handleFatalError(4, 'syntax error, u...', 'D:\xampp\htdocs...', 49)
#1 [internal function]: ErrorHandler::handleError(4, 'syntax error, u...', 'D:\xampp\htdocs...', 49, Array)
#2 D:\xampp\htdocs\cakephp\lib\Cake\Core\App.php(931): call_user_func('ErrorHandler::h...', 4, 'syntax error, u...', 'D:\xampp\htdocs...', 49, Array)
#3 D:\xampp\htdocs\cakephp\lib\Cake\Core\App.php(904): App::_checkFatalError()
#4 [internal function]: App::shutdown()
#5 {main}
2013-11-22 14:14:28 Error: Fatal Error (4): syntax error, unexpected ')', expecting ',' or ';' in [D:\xampp\htdocs\cakephp\app\Controller\AppController.php, line 49]
2013-11-22 14:14:28 Error: [FatalErrorException] syntax error, unexpected ')', expecting ',' or ';'
Request URL: /cakephp/
Stack Trace:
#0 D:\xampp\htdocs\cakephp\lib\Cake\Error\ErrorHandler.php(205): ErrorHandler::handleFatalError(4, 'syntax error, u...', 'D:\xampp\htdocs...', 49)
#1 [internal function]: ErrorHandler::handleError(4, 'syntax error, u...', 'D:\xampp\htdocs...', 49, Array)
#2 D:\xampp\htdocs\cakephp\lib\Cake\Core\App.php(931): call_user_func('ErrorHandler::h...', 4, 'syntax error, u...', 'D:\xampp\htdocs...', 49, Array)
#3 D:\xampp\htdocs\cakephp\lib\Cake\Core\App.php(904): App::_checkFatalError()
#4 [internal function]: App::shutdown()
#5 {main}
2013-11-22 14:15:19 Error: [CakeException] Authentication adapter "User" was not found.
Request URL: /cakephp/
Stack Trace:
#0 D:\xampp\htdocs\cakephp\lib\Cake\Controller\Component\AuthComponent.php(675): AuthComponent->constructAuthenticate()
#1 D:\xampp\htdocs\cakephp\lib\Cake\Controller\Component\AuthComponent.php(303): AuthComponent->_getUser()
#2 [internal function]: AuthComponent->startup(Object(PagesController))
#3 D:\xampp\htdocs\cakephp\lib\Cake\Utility\ObjectCollection.php(132): call_user_func_array(Array, Array)
#4 [internal function]: ObjectCollection->trigger(Object(CakeEvent))
#5 D:\xampp\htdocs\cakephp\lib\Cake\Event\CakeEventManager.php(248): call_user_func(Array, Object(CakeEvent))
#6 D:\xampp\htdocs\cakephp\lib\Cake\Controller\Controller.php(675): CakeEventManager->dispatch(Object(CakeEvent))
#7 D:\xampp\htdocs\cakephp\lib\Cake\Routing\Dispatcher.php(184): Controller->startupProcess()
#8 D:\xampp\htdocs\cakephp\lib\Cake\Routing\Dispatcher.php(162): Dispatcher->_invoke(Object(PagesController), Object(CakeRequest), Object(CakeResponse))
#9 D:\xampp\htdocs\cakephp\app\webroot\index.php(110): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#10 {main}
2013-11-22 14:15:29 Error: [CakeException] Authentication adapter "User" was not found.
Request URL: /cakephp/users/login
Stack Trace:
#0 D:\xampp\htdocs\cakephp\lib\Cake\Controller\Component\AuthComponent.php(675): AuthComponent->constructAuthenticate()
#1 D:\xampp\htdocs\cakephp\lib\Cake\Controller\Component\AuthComponent.php(303): AuthComponent->_getUser()
#2 [internal function]: AuthComponent->startup(Object(UsersController))
#3 D:\xampp\htdocs\cakephp\lib\Cake\Utility\ObjectCollection.php(132): call_user_func_array(Array, Array)
#4 [internal function]: ObjectCollection->trigger(Object(CakeEvent))
#5 D:\xampp\htdocs\cakephp\lib\Cake\Event\CakeEventManager.php(248): call_user_func(Array, Object(CakeEvent))
#6 D:\xampp\htdocs\cakephp\lib\Cake\Controller\Controller.php(675): CakeEventManager->dispatch(Object(CakeEvent))
#7 D:\xampp\htdocs\cakephp\lib\Cake\Routing\Dispatcher.php(184): Controller->startupProcess()
#8 D:\xampp\htdocs\cakephp\lib\Cake\Routing\Dispatcher.php(162): Dispatcher->_invoke(Object(UsersController), Object(CakeRequest), Object(CakeResponse))
#9 D:\xampp\htdocs\cakephp\app\webroot\index.php(110): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#10 {main}
2013-11-22 14:16:08 Error: Fatal Error (1): Call to a member function allow() on a non-object in [D:\xampp\htdocs\cakephp\app\Controller\UsersController.php, line 22]
2013-11-22 14:16:08 Error: [FatalErrorException] Call to a member function allow() on a non-object
Request URL: /cakephp/users/login
Stack Trace:
#0 D:\xampp\htdocs\cakephp\lib\Cake\Error\ErrorHandler.php(205): ErrorHandler::handleFatalError(1, 'Call to a membe...', 'D:\xampp\htdocs...', 22)
#1 [internal function]: ErrorHandler::handleError(1, 'Call to a membe...', 'D:\xampp\htdocs...', 22, Array)
#2 D:\xampp\htdocs\cakephp\lib\Cake\Core\App.php(931): call_user_func('ErrorHandler::h...', 1, 'Call to a membe...', 'D:\xampp\htdocs...', 22, Array)
#3 D:\xampp\htdocs\cakephp\lib\Cake\Core\App.php(904): App::_checkFatalError()
#4 [internal function]: App::shutdown()
#5 {main}
2013-11-22 14:22:33 Error: Fatal Error (1): Call to a member function allow() on a non-object in [D:\xampp\htdocs\cakephp\app\Controller\UsersController.php, line 22]
2013-11-22 14:22:33 Error: [FatalErrorException] Call to a member function allow() on a non-object
Request URL: /cakephp/users/login
Stack Trace:
#0 D:\xampp\htdocs\cakephp\lib\Cake\Error\ErrorHandler.php(205): ErrorHandler::handleFatalError(1, 'Call to a membe...', 'D:\xampp\htdocs...', 22)
#1 [internal function]: ErrorHandler::handleError(1, 'Call to a membe...', 'D:\xampp\htdocs...', 22, Array)
#2 D:\xampp\htdocs\cakephp\lib\Cake\Core\App.php(931): call_user_func('ErrorHandler::h...', 1, 'Call to a membe...', 'D:\xampp\htdocs...', 22, Array)
#3 D:\xampp\htdocs\cakephp\lib\Cake\Core\App.php(904): App::_checkFatalError()
#4 [internal function]: App::shutdown()
#5 {main}
2013-11-22 14:23:40 Error: [MissingComponentException] Component class FormfuncComponent could not be found.
Exception Attributes: array (
  'class' => 'FormfuncComponent',
  'plugin' => false,
)
Request URL: /cakephp/system
Stack Trace:
#0 D:\xampp\htdocs\cakephp\lib\Cake\Controller\ComponentCollection.php(53): ComponentCollection->load('Formfunc', Array)
#1 D:\xampp\htdocs\cakephp\lib\Cake\Controller\Controller.php(643): ComponentCollection->init(Object(SystemController))
#2 D:\xampp\htdocs\cakephp\lib\Cake\Routing\Dispatcher.php(183): Controller->constructClasses()
#3 D:\xampp\htdocs\cakephp\lib\Cake\Routing\Dispatcher.php(162): Dispatcher->_invoke(Object(SystemController), Object(CakeRequest), Object(CakeResponse))
#4 D:\xampp\htdocs\cakephp\app\webroot\index.php(110): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#5 {main}
2013-11-22 14:24:47 Error: [MissingComponentException] Component class TakeStockFuncComponent could not be found.
Exception Attributes: array (
  'class' => 'TakeStockFuncComponent',
  'plugin' => false,
)
Request URL: /cakephp/system
Stack Trace:
#0 D:\xampp\htdocs\cakephp\lib\Cake\Controller\ComponentCollection.php(53): ComponentCollection->load('TakeStockFunc', Array)
#1 D:\xampp\htdocs\cakephp\lib\Cake\Controller\Controller.php(643): ComponentCollection->init(Object(SystemController))
#2 D:\xampp\htdocs\cakephp\lib\Cake\Routing\Dispatcher.php(183): Controller->constructClasses()
#3 D:\xampp\htdocs\cakephp\lib\Cake\Routing\Dispatcher.php(162): Dispatcher->_invoke(Object(SystemController), Object(CakeRequest), Object(CakeResponse))
#4 D:\xampp\htdocs\cakephp\app\webroot\index.php(110): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#5 {main}
2013-11-22 14:25:39 Error: [MissingActionException] Action SystemController::index() could not be found.
Exception Attributes: array (
  'controller' => 'SystemController',
  'action' => 'index',
)
Request URL: /cakephp/system
Stack Trace:
#0 D:\xampp\htdocs\cakephp\lib\Cake\Routing\Dispatcher.php(187): Controller->invokeAction(Object(CakeRequest))
#1 D:\xampp\htdocs\cakephp\lib\Cake\Routing\Dispatcher.php(162): Dispatcher->_invoke(Object(SystemController), Object(CakeRequest), Object(CakeResponse))
#2 D:\xampp\htdocs\cakephp\app\webroot\index.php(110): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#3 {main}
2013-11-22 14:25:51 Error: [MissingControllerException] Controller class SystemsController could not be found.
Exception Attributes: array (
  'class' => 'SystemsController',
  'plugin' => NULL,
)
Request URL: /cakephp/systems
Stack Trace:
#0 D:\xampp\htdocs\cakephp\app\webroot\index.php(110): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#1 {main}
2013-11-22 14:25:55 Error: [MissingActionException] Action SystemController::index() could not be found.
Exception Attributes: array (
  'controller' => 'SystemController',
  'action' => 'index',
)
Request URL: /cakephp/system
Stack Trace:
#0 D:\xampp\htdocs\cakephp\lib\Cake\Routing\Dispatcher.php(187): Controller->invokeAction(Object(CakeRequest))
#1 D:\xampp\htdocs\cakephp\lib\Cake\Routing\Dispatcher.php(162): Dispatcher->_invoke(Object(SystemController), Object(CakeRequest), Object(CakeResponse))
#2 D:\xampp\htdocs\cakephp\app\webroot\index.php(110): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#3 {main}
2013-11-22 14:29:03 Error: [PDOException] SQLSTATE[42S22]: Column not found: 1054 Unknown column 'valid' in 'order clause'
Request URL: /cakephp/system/dep_index
Stack Trace:
#0 D:\xampp\htdocs\cakephp\lib\Cake\Model\Datasource\DboSource.php(460): PDOStatement->execute(Array)
#1 D:\xampp\htdocs\cakephp\lib\Cake\Model\Datasource\DboSource.php(426): DboSource->_execute('SELECT `Departm...', Array)
#2 D:\xampp\htdocs\cakephp\lib\Cake\Model\Datasource\DboSource.php(666): DboSource->execute('SELECT `Departm...', Array, Array)
#3 D:\xampp\htdocs\cakephp\lib\Cake\Model\Datasource\DboSource.php(1077): DboSource->fetchAll('SELECT `Departm...', false)
#4 D:\xampp\htdocs\cakephp\lib\Cake\Model\Model.php(2880): DboSource->read(Object(Department), Array)
#5 D:\xampp\htdocs\cakephp\lib\Cake\Model\Model.php(2852): Model->_readDataSource('all', Array)
#6 D:\xampp\htdocs\cakephp\app\Controller\SystemController.php(8): Model->find('all', Array)
#7 [internal function]: SystemController->dep_index()
#8 D:\xampp\htdocs\cakephp\lib\Cake\Controller\Controller.php(490): ReflectionMethod->invokeArgs(Object(SystemController), Array)
#9 D:\xampp\htdocs\cakephp\lib\Cake\Routing\Dispatcher.php(187): Controller->invokeAction(Object(CakeRequest))
#10 D:\xampp\htdocs\cakephp\lib\Cake\Routing\Dispatcher.php(162): Dispatcher->_invoke(Object(SystemController), Object(CakeRequest), Object(CakeResponse))
#11 D:\xampp\htdocs\cakephp\app\webroot\index.php(110): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#12 {main}
2013-11-22 14:33:46 Error: [MissingViewException] View file "D:\xampp\htdocs\cakephp\app\View\System\dep_index.ctp" is missing.
Exception Attributes: array (
  'file' => 'D:\\xampp\\htdocs\\cakephp\\app\\View\\System\\dep_index.ctp',
)
Request URL: /cakephp/system/dep_index
Stack Trace:
#0 D:\xampp\htdocs\cakephp\lib\Cake\View\View.php(459): View->_getViewFileName(NULL)
#1 D:\xampp\htdocs\cakephp\lib\Cake\Controller\Controller.php(952): View->render(NULL, NULL)
#2 D:\xampp\htdocs\cakephp\lib\Cake\Routing\Dispatcher.php(194): Controller->render()
#3 D:\xampp\htdocs\cakephp\lib\Cake\Routing\Dispatcher.php(162): Dispatcher->_invoke(Object(SystemController), Object(CakeRequest), Object(CakeResponse))
#4 D:\xampp\htdocs\cakephp\app\webroot\index.php(110): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#5 {main}
2013-11-22 14:54:07 Error: [MissingViewException] View file "D:\xampp\htdocs\cakephp\app\View\System\dep_index.ctp" is missing.
Exception Attributes: array (
  'file' => 'D:\\xampp\\htdocs\\cakephp\\app\\View\\System\\dep_index.ctp',
)
Request URL: /cakephp/system/dep_index
Stack Trace:
#0 D:\xampp\htdocs\cakephp\lib\Cake\View\View.php(459): View->_getViewFileName(NULL)
#1 D:\xampp\htdocs\cakephp\lib\Cake\Controller\Controller.php(952): View->render(NULL, NULL)
#2 D:\xampp\htdocs\cakephp\lib\Cake\Routing\Dispatcher.php(194): Controller->render()
#3 D:\xampp\htdocs\cakephp\lib\Cake\Routing\Dispatcher.php(162): Dispatcher->_invoke(Object(SystemController), Object(CakeRequest), Object(CakeResponse))
#4 D:\xampp\htdocs\cakephp\app\webroot\index.php(110): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#5 {main}
2013-11-22 15:03:10 Error: Fatal Error (4): syntax error, unexpected ''User'' (T_CONSTANT_ENCAPSED_STRING), expecting ')' in [D:\xampp\htdocs\cakephp\app\Controller\SystemController.php, line 3]
2013-11-22 15:03:10 Error: [FatalErrorException] syntax error, unexpected ''User'' (T_CONSTANT_ENCAPSED_STRING), expecting ')'
Request URL: /cakephp/system/dep_list
Stack Trace:
#0 D:\xampp\htdocs\cakephp\lib\Cake\Error\ErrorHandler.php(205): ErrorHandler::handleFatalError(4, 'syntax error, u...', 'D:\xampp\htdocs...', 3)
#1 [internal function]: ErrorHandler::handleError(4, 'syntax error, u...', 'D:\xampp\htdocs...', 3, Array)
#2 D:\xampp\htdocs\cakephp\lib\Cake\Core\App.php(931): call_user_func('ErrorHandler::h...', 4, 'syntax error, u...', 'D:\xampp\htdocs...', 3, Array)
#3 D:\xampp\htdocs\cakephp\lib\Cake\Core\App.php(904): App::_checkFatalError()
#4 [internal function]: App::shutdown()
#5 {main}
2013-11-22 15:04:50 Error: [PDOException] SQLSTATE[23000]: Integrity constraint violation: 1062 Duplicate entry '' for key 'PRIMARY'
Request URL: /cakephp/system/prj_del
Stack Trace:
#0 D:\xampp\htdocs\cakephp\lib\Cake\Model\Datasource\DboSource.php(460): PDOStatement->execute(Array)
#1 D:\xampp\htdocs\cakephp\lib\Cake\Model\Datasource\DboSource.php(426): DboSource->_execute('INSERT INTO `la...', Array)
#2 D:\xampp\htdocs\cakephp\lib\Cake\Model\Datasource\DboSource.php(1004): DboSource->execute('INSERT INTO `la...')
#3 D:\xampp\htdocs\cakephp\lib\Cake\Model\Model.php(1827): DboSource->create(Object(AppModel), Array, Array)
#4 D:\xampp\htdocs\cakephp\app\Controller\SystemController.php(75): Model->save(Array)
#5 [internal function]: SystemController->prj_del()
#6 D:\xampp\htdocs\cakephp\lib\Cake\Controller\Controller.php(490): ReflectionMethod->invokeArgs(Object(SystemController), Array)
#7 D:\xampp\htdocs\cakephp\lib\Cake\Routing\Dispatcher.php(187): Controller->invokeAction(Object(CakeRequest))
#8 D:\xampp\htdocs\cakephp\lib\Cake\Routing\Dispatcher.php(162): Dispatcher->_invoke(Object(SystemController), Object(CakeRequest), Object(CakeResponse))
#9 D:\xampp\htdocs\cakephp\app\webroot\index.php(110): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#10 {main}
2013-11-22 15:04:50 Error: Fatal Error (1): Uncaught exception 'Exception' with message 'Headers already sent in D:\xampp\htdocs\cakephp\lib\Cake\Utility\Debugger.php on line 804. Cannot send log data to FirePHP. You must have Output Buffering enabled via ob_start() or output_buffering ini directive.' in D:\xampp\htdocs\cakephp\app\Vendor\FirePHPCore\FirePHP.class.php:1178
Stack trace:
#0 D:\xampp\htdocs\cakephp\app\Vendor\FirePHPCore\FirePHP.class.php(757): FirePHP->newException('Headers already...')
#1 D:\xampp\htdocs\cakephp\app\Vendor\FirePHPCore\FirePHP.class.php(584): FirePHP->fb('error', '2013-11-22 15:0...', 'LOG', Array)
#2 D:\xampp\htdocs\cakephp\app\Lib\Log\Engine\FirePHPLog.php(104): FirePHP->log('error', '2013-11-22 15:0...')
#3 D:\xampp\htdocs\cakephp\lib\Cake\Log\CakeLog.php(454): FirePHPLog->write('error', '[PDOException] ...')
#4 D:\xampp\htdocs\cakephp\lib\Cake\Error\ErrorHandler.php(180): CakeLog::write(4, '[PDOException] ...')
#5 D:\xampp\htdocs\cakephp\lib\Cake\Error\ErrorHandler.php(113): ErrorHandler::_log(Object(PDOException), A in [D:\xampp\htdocs\cakephp\app\Vendor\FirePHPCore\FirePHP.class.php, line 1178]
2013-11-22 15:26:50 Error: [MissingTableException] Table meeting_rooms for model MeetingRoom was not found in datasource default.
Exception Attributes: array (
  'table' => 'meeting_rooms',
  'class' => 'MeetingRoom',
  'ds' => 'default',
)
Request URL: /cakephp/system/mr_list
Stack Trace:
#0 D:\xampp\htdocs\cakephp\lib\Cake\Model\Model.php(3476): Model->setSource('meeting_rooms')
#1 D:\xampp\htdocs\cakephp\lib\Cake\Model\Model.php(2880): Model->getDataSource()
#2 D:\xampp\htdocs\cakephp\lib\Cake\Model\Model.php(2852): Model->_readDataSource('all', Array)
#3 D:\xampp\htdocs\cakephp\app\Controller\SystemController.php(84): Model->find('all', Array)
#4 [internal function]: SystemController->mr_list()
#5 D:\xampp\htdocs\cakephp\lib\Cake\Controller\Controller.php(490): ReflectionMethod->invokeArgs(Object(SystemController), Array)
#6 D:\xampp\htdocs\cakephp\lib\Cake\Routing\Dispatcher.php(187): Controller->invokeAction(Object(CakeRequest))
#7 D:\xampp\htdocs\cakephp\lib\Cake\Routing\Dispatcher.php(162): Dispatcher->_invoke(Object(SystemController), Object(CakeRequest), Object(CakeResponse))
#8 D:\xampp\htdocs\cakephp\app\webroot\index.php(110): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#9 {main}
2013-11-22 15:59:36 Error: Fatal Error (1): Class 'AuthComponent' not found in [D:\xampp\htdocs\cakephp\app\Model\User.php, line 28]
2013-11-22 15:59:36 Error: [FatalErrorException] Class 'AuthComponent' not found
Request URL: /cakephp/system/user_del/1
Stack Trace:
#0 D:\xampp\htdocs\cakephp\lib\Cake\Error\ErrorHandler.php(205): ErrorHandler::handleFatalError(1, 'Class 'AuthComp...', 'D:\xampp\htdocs...', 28)
#1 [internal function]: ErrorHandler::handleError(1, 'Class 'AuthComp...', 'D:\xampp\htdocs...', 28, Array)
#2 D:\xampp\htdocs\cakephp\lib\Cake\Core\App.php(931): call_user_func('ErrorHandler::h...', 1, 'Class 'AuthComp...', 'D:\xampp\htdocs...', 28, Array)
#3 D:\xampp\htdocs\cakephp\lib\Cake\Core\App.php(904): App::_checkFatalError()
#4 [internal function]: App::shutdown()
#5 {main}
2013-11-22 16:02:10 Error: Fatal Error (1): Class 'AuthComponent' not found in [D:\xampp\htdocs\cakephp\app\Model\User.php, line 28]
2013-11-22 16:02:10 Error: [FatalErrorException] Class 'AuthComponent' not found
Request URL: /cakephp/system/user_del/1
Stack Trace:
#0 D:\xampp\htdocs\cakephp\lib\Cake\Error\ErrorHandler.php(205): ErrorHandler::handleFatalError(1, 'Class 'AuthComp...', 'D:\xampp\htdocs...', 28)
#1 [internal function]: ErrorHandler::handleError(1, 'Class 'AuthComp...', 'D:\xampp\htdocs...', 28, Array)
#2 D:\xampp\htdocs\cakephp\lib\Cake\Core\App.php(931): call_user_func('ErrorHandler::h...', 1, 'Class 'AuthComp...', 'D:\xampp\htdocs...', 28, Array)
#3 D:\xampp\htdocs\cakephp\lib\Cake\Core\App.php(904): App::_checkFatalError()
#4 [internal function]: App::shutdown()
#5 {main}
2013-11-22 16:05:15 Error: Fatal Error (1): Class 'Auth' not found in [D:\xampp\htdocs\cakephp\app\Model\User.php, line 28]
2013-11-22 16:05:15 Error: [FatalErrorException] Class 'Auth' not found
Request URL: /cakephp/system/user_del/1
Stack Trace:
#0 D:\xampp\htdocs\cakephp\lib\Cake\Error\ErrorHandler.php(205): ErrorHandler::handleFatalError(1, 'Class 'Auth' no...', 'D:\xampp\htdocs...', 28)
#1 [internal function]: ErrorHandler::handleError(1, 'Class 'Auth' no...', 'D:\xampp\htdocs...', 28, Array)
#2 D:\xampp\htdocs\cakephp\lib\Cake\Core\App.php(931): call_user_func('ErrorHandler::h...', 1, 'Class 'Auth' no...', 'D:\xampp\htdocs...', 28, Array)
#3 D:\xampp\htdocs\cakephp\lib\Cake\Core\App.php(904): App::_checkFatalError()
#4 [internal function]: App::shutdown()
#5 {main}
2013-11-22 16:19:55 Error: Fatal Error (4): syntax error, unexpected ''message'' (T_CONSTANT_ENCAPSED_STRING), expecting ')' in [D:\xampp\htdocs\cakephp\app\Model\User.php, line 19]
2013-11-22 16:20:29 Error: Fatal Error (4): syntax error, unexpected ''name'' (T_CONSTANT_ENCAPSED_STRING), expecting variable (T_VARIABLE) in [D:\xampp\htdocs\cakephp\app\Model\User.php, line 23]
2013-11-22 16:21:10 Error: Fatal Error (4): syntax error, unexpected ''name'' (T_CONSTANT_ENCAPSED_STRING), expecting variable (T_VARIABLE) in [D:\xampp\htdocs\cakephp\app\Model\User.php, line 23]
2013-11-22 16:21:15 Error: Fatal Error (4): syntax error, unexpected ''name'' (T_CONSTANT_ENCAPSED_STRING), expecting variable (T_VARIABLE) in [D:\xampp\htdocs\cakephp\app\Model\User.php, line 23]
2013-11-22 16:30:32 Error: [PDOException] SQLSTATE[42S22]: Column not found: 1054 Unknown column 'Department.user_id' in 'on clause'
Request URL: /cakephp/system/user_list
Stack Trace:
#0 D:\xampp\htdocs\cakephp\lib\Cake\Model\Datasource\DboSource.php(460): PDOStatement->execute(Array)
#1 D:\xampp\htdocs\cakephp\lib\Cake\Model\Datasource\DboSource.php(426): DboSource->_execute('SELECT `User`.`...', Array)
#2 D:\xampp\htdocs\cakephp\lib\Cake\Model\Datasource\DboSource.php(666): DboSource->execute('SELECT `User`.`...', Array, Array)
#3 D:\xampp\htdocs\cakephp\lib\Cake\Model\Datasource\DboSource.php(1077): DboSource->fetchAll('SELECT `User`.`...', false)
#4 D:\xampp\htdocs\cakephp\lib\Cake\Model\Model.php(2880): DboSource->read(Object(User), Array)
#5 D:\xampp\htdocs\cakephp\lib\Cake\Model\Model.php(2852): Model->_readDataSource('all', Array)
#6 D:\xampp\htdocs\cakephp\app\Controller\SystemController.php(120): Model->find('all', Array)
#7 [internal function]: SystemController->user_list()
#8 D:\xampp\htdocs\cakephp\lib\Cake\Controller\Controller.php(490): ReflectionMethod->invokeArgs(Object(SystemController), Array)
#9 D:\xampp\htdocs\cakephp\lib\Cake\Routing\Dispatcher.php(187): Controller->invokeAction(Object(CakeRequest))
#10 D:\xampp\htdocs\cakephp\lib\Cake\Routing\Dispatcher.php(162): Dispatcher->_invoke(Object(SystemController), Object(CakeRequest), Object(CakeResponse))
#11 D:\xampp\htdocs\cakephp\app\webroot\index.php(110): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#12 {main}
2013-11-22 16:31:54 Error: [PDOException] SQLSTATE[42S22]: Column not found: 1054 Unknown column 'User.department_id' in 'on clause'
Request URL: /cakephp/system/user_list
Stack Trace:
#0 D:\xampp\htdocs\cakephp\lib\Cake\Model\Datasource\DboSource.php(460): PDOStatement->execute(Array)
#1 D:\xampp\htdocs\cakephp\lib\Cake\Model\Datasource\DboSource.php(426): DboSource->_execute('SELECT `User`.`...', Array)
#2 D:\xampp\htdocs\cakephp\lib\Cake\Model\Datasource\DboSource.php(666): DboSource->execute('SELECT `User`.`...', Array, Array)
#3 D:\xampp\htdocs\cakephp\lib\Cake\Model\Datasource\DboSource.php(1077): DboSource->fetchAll('SELECT `User`.`...', false)
#4 D:\xampp\htdocs\cakephp\lib\Cake\Model\Model.php(2880): DboSource->read(Object(User), Array)
#5 D:\xampp\htdocs\cakephp\lib\Cake\Model\Model.php(2852): Model->_readDataSource('all', Array)
#6 D:\xampp\htdocs\cakephp\app\Controller\SystemController.php(120): Model->find('all', Array)
#7 [internal function]: SystemController->user_list()
#8 D:\xampp\htdocs\cakephp\lib\Cake\Controller\Controller.php(490): ReflectionMethod->invokeArgs(Object(SystemController), Array)
#9 D:\xampp\htdocs\cakephp\lib\Cake\Routing\Dispatcher.php(187): Controller->invokeAction(Object(CakeRequest))
#10 D:\xampp\htdocs\cakephp\lib\Cake\Routing\Dispatcher.php(162): Dispatcher->_invoke(Object(SystemController), Object(CakeRequest), Object(CakeResponse))
#11 D:\xampp\htdocs\cakephp\app\webroot\index.php(110): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#12 {main}
2013-11-22 16:32:54 Error: [PDOException] SQLSTATE[23000]: Integrity constraint violation: 1052 Column 'valid' in order clause is ambiguous
Request URL: /cakephp/system/user_list
Stack Trace:
#0 D:\xampp\htdocs\cakephp\lib\Cake\Model\Datasource\DboSource.php(460): PDOStatement->execute(Array)
#1 D:\xampp\htdocs\cakephp\lib\Cake\Model\Datasource\DboSource.php(426): DboSource->_execute('SELECT `User`.`...', Array)
#2 D:\xampp\htdocs\cakephp\lib\Cake\Model\Datasource\DboSource.php(666): DboSource->execute('SELECT `User`.`...', Array, Array)
#3 D:\xampp\htdocs\cakephp\lib\Cake\Model\Datasource\DboSource.php(1077): DboSource->fetchAll('SELECT `User`.`...', false)
#4 D:\xampp\htdocs\cakephp\lib\Cake\Model\Model.php(2880): DboSource->read(Object(User), Array)
#5 D:\xampp\htdocs\cakephp\lib\Cake\Model\Model.php(2852): Model->_readDataSource('all', Array)
#6 D:\xampp\htdocs\cakephp\app\Controller\SystemController.php(120): Model->find('all', Array)
#7 [internal function]: SystemController->user_list()
#8 D:\xampp\htdocs\cakephp\lib\Cake\Controller\Controller.php(490): ReflectionMethod->invokeArgs(Object(SystemController), Array)
#9 D:\xampp\htdocs\cakephp\lib\Cake\Routing\Dispatcher.php(187): Controller->invokeAction(Object(CakeRequest))
#10 D:\xampp\htdocs\cakephp\lib\Cake\Routing\Dispatcher.php(162): Dispatcher->_invoke(Object(SystemController), Object(CakeRequest), Object(CakeResponse))
#11 D:\xampp\htdocs\cakephp\app\webroot\index.php(110): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#12 {main}
2013-11-22 16:34:59 Error: [PDOException] SQLSTATE[23000]: Integrity constraint violation: 1052 Column 'id' in order clause is ambiguous
Request URL: /cakephp/system/user_list
Stack Trace:
#0 D:\xampp\htdocs\cakephp\lib\Cake\Model\Datasource\DboSource.php(460): PDOStatement->execute(Array)
#1 D:\xampp\htdocs\cakephp\lib\Cake\Model\Datasource\DboSource.php(426): DboSource->_execute('SELECT `User`.`...', Array)
#2 D:\xampp\htdocs\cakephp\lib\Cake\Model\Datasource\DboSource.php(666): DboSource->execute('SELECT `User`.`...', Array, Array)
#3 D:\xampp\htdocs\cakephp\lib\Cake\Model\Datasource\DboSource.php(1077): DboSource->fetchAll('SELECT `User`.`...', false)
#4 D:\xampp\htdocs\cakephp\lib\Cake\Model\Model.php(2880): DboSource->read(Object(User), Array)
#5 D:\xampp\htdocs\cakephp\lib\Cake\Model\Model.php(2852): Model->_readDataSource('all', Array)
#6 D:\xampp\htdocs\cakephp\app\Controller\SystemController.php(116): Model->find('all', Array)
#7 [internal function]: SystemController->user_list()
#8 D:\xampp\htdocs\cakephp\lib\Cake\Controller\Controller.php(490): ReflectionMethod->invokeArgs(Object(SystemController), Array)
#9 D:\xampp\htdocs\cakephp\lib\Cake\Routing\Dispatcher.php(187): Controller->invokeAction(Object(CakeRequest))
#10 D:\xampp\htdocs\cakephp\lib\Cake\Routing\Dispatcher.php(162): Dispatcher->_invoke(Object(SystemController), Object(CakeRequest), Object(CakeResponse))
#11 D:\xampp\htdocs\cakephp\app\webroot\index.php(110): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#12 {main}
